### ISSUE TITLE
Sorting ends of Voronoi diagram edges.

### ISSUE THREAD

**Issue by tomilov** [Morwenn/vergesort#10]
There is a Voronoi diagram. For compactly located cloud of points it looks like this:
![sun](https://cloud.githubusercontent.com/assets/896175/24325327/580d0812-11b8-11e7-96d9-9ab92c416ca6.png)
As you can see it is a simple graph. A set of connected edges, which not corss each other. Some of them are rays (on the periphery), another ones are sections (also it is possible a strait line case, but it is not too interesting corner case).
x-coordinate of the begins of the edges have the following distribution (in order of construction of them by Fortune's algorithm):
![begins](https://cloud.githubusercontent.com/assets/896175/24325348/d02ea526-11b8-11e7-916b-ac51a0e87822.png)
Corresponding distribution for ends is here: 
![ends](https://cloud.githubusercontent.com/assets/896175/24325353/f1f3ac74-11b8-11e7-87bf-def54539c0a9.png)
I.e. it is almost sorted set of objects. They are almost not sorted in a strip of almost constant height. There are a small subset of overshoots.

Does `vergesort` suitable for such a distribution?

Is there good precalc for data, to ease a work for some classic sorting algorithm?

**Comment by Morwenn** [comment]
Looking at your distributions, it looks like an *Inv*-adaptive or *Rem*-adaptive sorting algorithm would be better: vergesort works well when there are runs bigger than n / log n in the collection to sort, where n is the size of the collection to sort. In your case, while the distributions look mostly sorted, the sorted runs don't always look big enough. The main feature of these distributions does not seem to be "big sorted runs", but "few misplaced elements". For such a case an algorithm like [drop-merge sort](https://github.com/adrian17/cpp-drop-merge-sort) is probably more suitable than vergesort.

**Comment by tomilov** [comment]
@Morwenn Thank you.

**Comment by Morwenn** [comment]
No problem. Your Voronoi diagram is pretty by the way :3

**Comment by tomilov** [comment]
I just want to solve the problem of finding a nearest point from first set to each of points from second set using Fortune's algorithm (for M=100000 and N=10000 it faster then solution using AVX vectorization).
